require('nvim-treesitter.configs').setup({
	ensure_installed = {
		'awk',
		'bash',
		'c',
		'comment',
		'cpp',
		'css',
		'diff',
		'dockerfile',
		'gitattributes',
		'gitcommit',
		'gitignore',
		'go',
		'html',
		'http',
		'javascript',
		'jsdoc',
		'json',
		'lua',
		'make',
		'markdown',
		'markdown_inline',
		'php',
		'phpdoc',
		'python',
		'regex',
		'rust',
		'scss',
		'toml',
		'tsx',
		'twig',
		'typescript',
		'vim',
		'vue',
		'yaml',
	},
	highlight = {
		enable = true,
		disable = { 'NvimTree' },
		additional_vim_regex_highlighting = true,
	},
	textobjects = {
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				['if'] = '@function.inner',
				['af'] = '@function.outer',
				['ic'] = '@class.inner',
				['ac'] = '@class.outer',
				['ia'] = '@parameter.inner',
				['aa'] = '@parameter.outer',
			},
		},
	},
	context_commentstring = {
		enable = true,
	},
})

-- require('treesitter-context').setup({
--   enable = true,
--   max_lines = 0,
--   separator = '-',
-- })
