[font]
size = 16.0

[font.normal]
family = "MonaspaceArgon Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MonaspaceArgon Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MonaspaceArgon Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MonaspaceArgon Nerd Font Mono"
style = "Bold Italic"

[font.offset]
y = 25
