#!/usr/bin/env bash

if test -f /usr/bin/gnome-keyring-daemon
then
    eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
    export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
fi

xset s off &
xset -dpms &
xrdb -merge ~/.Xresources &
autocutsel -fork &
autocutsel -fork -selection PRIMARY &
#xmodmap ~/.keybindings &

# set resolution
xrandr | grep 1920x1080 | tail -1 >/dev/null
if test $? -eq 0
then
    xrandr --output VGA-0 --mode 1920x1080 &
fi

# set background
command -v feh >/dev/null
if [ $? -eq 0 -a -f ~/.background ]
then
    feh --bg-fill ~/.background
fi

exec i3
