#!/usr/bin/env zsh

alias ls='/bin/ls'

if ! test -d $HOME/.antigen ; then
    git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
fi

# setup antigen
source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle gitfast
antigen bundle git-extras
antigen bundle tmux
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme aknackd/zsh-themes arael
antigen apply

# separate dotfiles
dotfiles=( .functions .environment .aliases )
for filename in "${dotfiles[@]}"; do
    test -f $HOME/$filename && source $HOME/$filename
done
